---
title: "HW3 경제경영자료분석"
author: "박효선 1585063"
date: "2018년 10월 29일"
output:
  word_document: default

---
#HW 3
####Table 9.2. 모형 (4)에서의 설명 변수중 Unemployment rate를 빼고 재분석 합니다.
####logit모형을 적합시키고 모형에서 오즈비 추정의 차이를 계산합니다. 
#####단, 다른 변수들은 모두 평균을 사용합니다. 

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

setwd("C:/Users/HS/Documents/GitHub/Statistics-for-Management-and-Economy")
hmda.data<-read.csv("hmda.csv",header=TRUE)
head(hmda.data)

attach(hmda.data)
pi_rat<-s46/100                                      # P/I ratio
hse_inc<-s45/100                                     # housing expense-to-income ratio
ltv<-s6/s50                                          # loan-to-value ratio
ccred<-s43                                           # consumer credit score
mcred<-s42                                           # mortgage credit score
pubrec<-s44                                          # public bad credit record
denpmi<-s53                                          # denied mortgage insurance
selfemp<-s27a                                        # self-employed
single<-ifelse(s23a=="U",1,0)
hischl<-ifelse(school>=12,1,0)                       # high school diploma
probunmp<-uria                                   # probunmp(unemployment rate)
condo<-ifelse(s51==1,1,0)                          # condominium
black<-ifelse(s13==3,1,0)                 
deny<-ifelse(s7==3,1,0)

ltv_med<-ifelse(ltv>=0.85 & ltv<0.95,1,0)
ltv_high<-ifelse(ltv>=0.95,1,0)
blk_pi<-black*pi_rat
blk_hse<-black*hse_inc

mortdeny.data<-data.frame(pi_rat=pi_rat,hse_inc=hse_inc,ltv=ltv,ccred=ccred,mcred=mcred,pubrec=pubrec,
                          denpmi=denpmi,selfemp=selfemp,single=single,hischl=hischl,probunmp=probunmp,
                          condo=condo,black=black,deny=deny,ltv_high=ltv_high,blk_pi=blk_pi,blk_hse=blk_hse)    # 데이터 생성

```




```{r}
#mortdeny.data <- tbl_df(mortdeny.data)

names(mortdeny.data)
head(mortdeny.data)
apply(mortdeny.data, 2, mean)

```

```{r}

logit_model_4 <- glm( deny ~ black + pi_rat + hse_inc + ltv_med + ltv_high +
                        ccred + mcred + pubrec + denpmi + selfemp + single + 
                        hischl + condo, data = mortdeny.data, 
                      family = binomial(link = logit))

summary(logit_model_4)

```



###오즈비 추정 

```{r warning=FALSE}
#오즈비 추정 
OR <- exp(logit_model_4$coefficients)
OR.U <- exp(logit_model_4$coef + 1.96*summary(logit_model_4)$coef[,2])
OR.L <- exp(logit_model_4$coef - 1.96*summary(logit_model_4)$coef[,2])

```


###오즈비, 오즈비 95% 신뢰구간


- 흑인이 백인보다 기각 Odds 크다. 
- black의 Odds 신뢰구간 : (1.383813725, 2.8339224)
- 1을 포함하지 않는다. 흑인과 백인간의  차이는 유의하다.


```{r warning=FALSE}
#오즈비, 오즈비 95% 신뢰구간
cbind(OR, OR.L, OR.U)
```















