---
title: "HW 4 경경분"
author: "박효선 1585063"
date: "2018년 11월 15일"
output: word_document
---

```{r setup, include=FALSE}
library(AER)                                                   # 도구변수 회귀 package
library(lmtest)                                                # Heterosckedasticity Robust Standard Error package


setwd("C:/Users/HS/Documents/GitHub/Statistics-for-Management-and-Economy")
ciga.data = read.csv("ciga.csv",header=TRUE)                          # 데이터 불러오기

```

###필요한 변수 만들기

```{r}


attach(ciga.data)

rtaxso = taxs/cpi-tax/cpi                                             #sale tax
rtax = tax/cpi                                                        #ciga tax
perinc = income/pop/cpi                                               # real per capita state income


log.q = log(packpc[year==1995])-log(packpc[year==1985])               #ln(Q_1995)-ln(Q_1985)
log.p = log(avgprs[year==1995])-log(avgprs[year==1985])               #ln(P_1995)-ln(P_1985)
log.inc = log(perinc[year==1995])-log(perinc[year==1985])             #ln(income_1995)-ln(income_1985)
cigatax = rtax[year==1995]-rtax[year==1985]                           #CigTax_1995-CigTax_1985
saletax = rtaxso[year==1995]-rtaxso[year==1985]                       #SalesTax_1995-SalesTax_1985

head(ciga.data)
names(ciga.data)

```

###Model (1)


```{r }
# Model(1) 

# TSLS
model_1 <- ivreg(log.q ~ log.p + log.inc | saletax + log.inc)         
coeftest(model_1, vcov = vcovHC)                             

# 1st Stage
lm.x1 = lm(log.p ~ log.inc + saletax)
# X:담배가격, W:Income, Z(도구변수): Sale tax 1st stage linear regression
summary(lm.x1)$f
```


###Model (2)

```{r}
# Model(2)

# TSLS
model_2 <- ivreg(log.q ~ log.p + log.inc | cigatax + log.inc)         
coeftest(model_2, vcov = vcovHC)                             

# 1st Stage
lm.x2 = lm(log.p ~ log.inc + cigatax)                               
# X:담배가격, W:Income, Z(도구변수): Ciga tax 1st stage linear regression
summary(lm.x2)$f
```

###Model (3)

```{r}
# Model(3)

# TSLS
model_3 <- ivreg(log.q ~ log.p + log.inc | saletax + cigatax + log.inc)         
coeftest(model_3, vcov = vcovHC)                             

# 1st Stage
lm.x3 = lm(log.p ~ log.inc + saletax + cigatax)                               
# X:담배가격, W:Income, Z1: Sale tax, Z2: Ciga tax 1st stage linear regression
summary(lm.x3)$f

# 도구변수 외생성 검정
u.hat <- model_3$residuals
aux <- lm(u.hat ~ log.inc + saletax + cigatax)
m <- 2
k <- 1
J <- m * summary(aux)$f[1] # ~chisq(df = 2-1)
J
1-pchisq(J,1)

```

